

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors: ['枫溪']


depend: [AttributePlus]

lib-download: true
lib-version: ${libVersion}
api-version: 1.13